version: "{build}"

skip_tags: true

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1
  GOARCH: amd64
  GOVERSION: 1.5.3

clone_folder: c:\gopath\src\github.com\docker\machine

install:
  - set Path=c:\go\bin;%Path%
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-%GOARCH%.msi
  - msiexec /i go%GOVERSION%.windows-%GOARCH%.msi /q

build_script:
  - go build -i -o ./bin/docker-machine.exe ./cmd/machine.go

test_script:
  - powershell -Command go test -v ./libmachine/shell

deploy: off
